# Generated by Django 6.1.2 on 2026-10-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente_formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ambiente', models.CharField(max_length=50)),
                ('tipo_ambiente', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centro_formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('nombre_centro', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trimestre', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('year', models.IntegerField(verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('nombre_objeto', models.CharField(max_length=150)),
                ('marca_ingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('vida_estimada_util', models.CharField(blank=True, max_length=50, null=True)),
                ('ambientes', models.ManyToManyField(blank=True, to='BaseDatosSica.ambiente_formacion')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=100)),
                ('fecha_movimiento', models.DateField()),
                ('hora_movimiento', models.TimeField()),
                ('estado_movimiento', models.CharField(max_length=50)),
                ('ambiente_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='BaseDatosSica.ambiente_formacion')),
                ('ambiente_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='BaseDatosSica.ambiente_formacion')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosSica.elemento')),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_novedad', models.CharField(max_length=150)),
                ('tipo_novedad', models.CharField(max_length=100)),
                ('descripcion_novedad', models.TextField()),
                ('estado_novedad', models.CharField(max_length=50)),
                ('fecha_novedad', models.DateField()),
                ('evidencia_novedad', models.FileField(blank=True, null=True, upload_to='novedades_evidencias/')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosSica.elemento')),
            ],
        ),
        migrations.CreateModel(
            name='Sedes_centro_Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('centro_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosSica.centro_formacion')),
            ],
        ),
        migrations.AddField(
            model_name='ambiente_formacion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosSica.sedes_centro_formacion'),
        ),
        migrations.CreateModel(
            name='Tipo_objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosSica.categoria_objeto')),
            ],
        ),
        migrations.AddField(
            model_name='elemento',
            name='tipo_objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BaseDatosSica.tipo_objeto'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('num_doc', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('nombre_p', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('nombre_s', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('apellido_p', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('apellido_s', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('genero', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='BaseDatosSica.rol', verbose_name='Rol asignado')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_formacion', models.CharField(max_length=150)),
                ('dias_formacion', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=50)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosSica.ambiente_formacion')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosSica.trimestre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDatosSica.usuario', verbose_name='Instructor/Usuario asignado')),
            ],
        ),
    ]
